name=ESP32P4_ULP
version=0.0.1
author=Xorlent
maintainer=Xorlent <https://github.com/Xorlent>
sentence=LP Core (ULP) support for ESP32-P4 in Arduino-esp32.
paragraph=Exposes pre-built LP Core programs for the ESP32-P4 without requiring the ESP-IDF ulp component. Currently supports GPIO wakeup.
category=Device Control
url=https://github.com/Xorlent/ESP32P4_ULP
architectures=esp32
depends=